# Generated by Django 3.1.12 on 2025-02-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250209_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='drivers_license',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
