# Generated by Django 3.1.12 on 2025-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250209_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='features',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='number_of_seats',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck')], default='Sedan', max_length=20),
        ),
    ]
