# Generated by Django 3.1.12 on 2025-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250209_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
