# Generated by Django 5.1.6 on 2025-03-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review_vehicle_alter_address_id_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sparepart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sparepart'),
        ),
    ]
